// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressFillController from "./address_fill_controller.js"
application.register("address-fill", AddressFillController)

import ClearFormController from "./clear_form_controller.js"
application.register("clear-form", ClearFormController)

import ConditionsController from "./conditions_controller.js"
application.register("conditions", ConditionsController)

import ConsulteeEmailController from "./consultee_email_controller.js"
application.register("consultee-email", ConsulteeEmailController)

import ConsulteesController from "./consultees_controller.js"
application.register("consultees", ConsulteesController)

import DeleteRecordController from "./delete_record_controller.js"
application.register("delete-record", DeleteRecordController)

import EditFormController from "./edit_form_controller.js"
application.register("edit-form", EditFormController)

import LocalPoliciesController from "./local_policies_controller.js"
application.register("local-policies", LocalPoliciesController)

import NeighboursController from "./neighbours_controller.js"
application.register("neighbours", NeighboursController)

import PdfController from "./pdf_controller.js"
application.register("pdf", PdfController)

import PolygonSearchController from "./polygon_search_controller.js"
application.register("polygon-search", PolygonSearchController)

import ResetTextController from "./reset_text_controller.js"
application.register("reset-text", ResetTextController)

import ShowHideController from "./show_hide_controller.js"
application.register("show-hide", ShowHideController)

import ShowHideFormController from "./show_hide_form_controller.js"
application.register("show-hide-form", ShowHideFormController)

import ShowMoreTextController from "./show_more_text_controller.js"
application.register("show-more-text", ShowMoreTextController)

import SubmitFormController from "./submit_form_controller.js"
application.register("submit-form", SubmitFormController)

import UnsavedChangesController from "./unsaved_changes_controller.js"
application.register("unsaved-changes", UnsavedChangesController)
