// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// biome-ignore-start assist/source/organizeImports: autogenerated code
import { application } from "./application"

import AddressFillController from "./address_fill_controller.js"
application.register("address-fill", AddressFillController)

import AddressSearchController from "./address_search_controller.js"
application.register("address-search", AddressSearchController)

import AutocompleteSelectController from "./autocomplete_select.js"
application.register("autocomplete-select", AutocompleteSelectController)

import AutoRefreshController from "./auto_refresh_controller.js"
application.register("auto-refresh", AutoRefreshController)

import AutoSubmitController from "./auto_submit_controller.js"
application.register("auto-submit", AutoSubmitController)

import ClearFormController from "./clear_form_controller.js"
application.register("clear-form", ClearFormController)

import ConditionsController from "./conditions_controller.js"
application.register("conditions", ConditionsController)

import ConsiderationFormController from "./consideration_form_controller.js"
application.register("consideration-form", ConsiderationFormController)

import ConsulteeEmailController from "./consultee_email_controller.js"
application.register("consultee-email", ConsulteeEmailController)

import ConsulteesController from "./consultees_controller.js"
application.register("consultees", ConsulteesController)

import DeleteRecordController from "./delete_record_controller.js"
application.register("delete-record", DeleteRecordController)

import DownloadController from "./download_controller.js"
application.register("download", DownloadController)

import EditFormController from "./edit_form_controller.js"
application.register("edit-form", EditFormController)

import InformativeFormController from "./informative_form_controller.js"
application.register("informative-form", InformativeFormController)

import LocalPoliciesController from "./local_policies_controller.js"
application.register("local-policies", LocalPoliciesController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import MaxLinesController from "./max_lines_controller.js"
application.register("max-lines", MaxLinesController)

import NeighboursController from "./neighbours_controller.js"
application.register("neighbours", NeighboursController)

import PdfController from "./pdf_controller.js"
application.register("pdf", PdfController)

import PolygonSearchController from "./polygon_search_controller.js"
application.register("polygon-search", PolygonSearchController)

import ResetTextController from "./reset_text_controller.js"
application.register("reset-text", ResetTextController)

import RichTextController from "@/bops_core/controllers/rich_text_controller.js"
application.register("rich-text", RichTextController)

import ShowHideController from "./show_hide_controller.js"
application.register("show-hide", ShowHideController)

import ShowHideFormController from "./show_hide_form_controller.js"
application.register("show-hide-form", ShowHideFormController)

import ShowMoreTextController from "./show_more_text_controller.js"
application.register("show-more-text", ShowMoreTextController)

import SiteNoticeController from "@/bops_core/controllers/site_notice_controller.js"
application.register("site-notice", SiteNoticeController)

import Sortable from "./sortable_controller.js"
application.register("sortable", Sortable)

import SubmitFormController from "./submit_form_controller.js"
application.register("submit-form", SubmitFormController)

import SummaryController from "@/bops_core/controllers/summary_controller.js"
application.register("summary", SummaryController)

import TaskAccordionController from "@/bops_core/controllers/task_accordion_controller.js"
application.register("task-accordion", TaskAccordionController)

import TaskAccordionSectionController from "@/bops_core/controllers/task_accordion_section_controller.js"
application.register("task-accordion-section", TaskAccordionSectionController)

import ToggleController from "./toggle_controller.js"
application.register("toggle", ToggleController)

import UnsavedChangesController from "./unsaved_changes_controller.js"
application.register("unsaved-changes", UnsavedChangesController)
// biome-ignore-end assist/source/organizeImports: autogenerated code
