---
inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  Exclude:
    - 'bops-applicants/**/*'
    - 'config/environments/**'
    - 'config/puma.rb'

Performance/CollectionLiteralInLoop:
  Exclude:
    - spec/models/planning_application_spec.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Exclude:
    - db/migrate/20210308183431_add_service_name_to_active_storage_blobs.active_storage.rb

# be a bit kinder with our metrics
Metrics/BlockLength:
  Max: 100
  Exclude:
    - spec/**/*
    - config/routes.rb

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Exclude:
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/models/review_policy_class_spec.rb

Naming/VariableNumber:
  Exclude:
    - spec/**/*
    - app/services/planning_application_creation_service.rb

# we tend to use update_all in migrations
Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*.rb

# Rspec
RSpec/MultipleExpectations:
  Enabled: false

Rails/NotNullColumn:
  Exclude:
    - db/migrate/20221116234525_add_review_mark_to_review_policy_classes.rb

Rails/RedundantPresenceValidationOnBelongsTo:
  Exclude:
    - app/models/validation_request.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - as
    - before
    - when
    - with
    - without

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb
