---
require:
  - standard
  - ./lib/bops/cop.rb

plugins:
  - rubocop-performance
  - rubocop-rails
  - standard-custom
  - standard-performance
  - standard-rails

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
  standard-rails: config/base.yml

AllCops:
  TargetRubyVersion: 3.4.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'config/environments/**'
    - 'config/puma.rb'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'engines/*/bin/*'

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true

Style/HaveCurrentPathLiteral:
  Enabled: true
  Exclude:
    - 'app/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
  IgnoreHelpers: []

Style/VisitLiteral:
  Enabled: true
  Exclude:
    - 'app/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
  IgnoreHelpers:
    - current_path

Style/NoFetchWithLiteralNilDefault:
  Enabled: true

Style/UseGovukLinkHelper:
  Enable: true

# We use the strong_migrations gem to catch any schema changes that might affect
# performance but it can't see what change_table does so don't require its use.
Rails/BulkChangeTable:
  Enabled: false

Rails/ReversibleMigration:
  Exclude:
    - db/migrate/202[0123]*

Rails/ReversibleMigrationMethodDefinition:
  Exclude:
    - db/migrate/202[0123]*

Rails/ThreeStateBooleanColumn:
  Exclude:
    - db/migrate/202[012]*
    - db/migrate/20230*
    - db/migrate/202310*

Rails/ApplicationJob:
  Exclude:
    # specs ignored so we can test concerns in isolation
    - engines/*/spec/**/*

# False positive: if being used in migrations, behaviour is different and intentional
Rails/ApplicationRecord:
  Exclude:
    - db/migrate/*

# Ignore scopes as Rails 7.0+ will find the inverse of automatically
Rails/InverseOf:
  IgnoreScopes: true

Rails/SaveBang:
  Exclude:
    # past migrations ignored, see above
    - db/migrate/202[0123]*
    # specs ignored because we might rely on this behaviour for testing errors
    - engines/*/spec/**/*
    - spec/**/*
