---
inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.5
  NewCops: enable
  Exclude:
    - 'bops-applicants/**/*'
    - 'lib/package_builder.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

# be a bit kinder with our metrics
Metrics/BlockLength:
  Max: 100
  Exclude:
    - spec/**/*
    - config/routes.rb

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Exclude:
    - spec/**/*

# we tend to use update_all in migrations
Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*.rb

# Rspec
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
