---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

# be a bit kinder with our metrics
Metrics/BlockLength:
  Max: 80

Metrics/MethodLength:
  Max: 20

# we tend to use update_all in migrations
Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*.rb
