---
services:
  web:
    environment:
      APPLICANTS_APP_HOST: http://southwark.southwark.applicants:3001
    networks:
      default:
        aliases:
          - southwark.southwark.web
    depends_on:
      - applicants
  applicants:
    environment:
      API_HOST: southwark.web:3333
    networks:
      default:
        aliases:
          - southwark.southwark.applicants
