// biome-ignore-start assist/source/organizeImports: autogenerated code
import { Application } from "@hotwired/stimulus"

const application = Application.start()
application.debug = false
window.Stimulus = application

import AddressFillController from "./address_fill_controller.js"
application.register("address-fill", AddressFillController)

import SiteNoticeController from "@/bops_core/controllers/site_notice_controller.js"
application.register("site-notice", SiteNoticeController)
// biome-ignore-end assist/source/organizeImports: autogenerated code
