business_time:
  beginning_of_workday: 9:00 am
  end_of_workday: 5:00 pm
  holidays:
    - December 27th, 2021
    - December 28th, 2021
    - Jan 03, 2022
    - April 15th, 2022
    - April 18th, 2022
    - May 02, 2022
    - June 02, 2022
    - June 03, 2022
    - August 29th, 2022
    - December 26th, 2022
    - December 27th, 2022
    - Jan 01, 2023
    - Jan 02, 2023
    - April 07, 2023
    - April 10th, 2023
    - May 01, 2023
    - May 29th, 2023
    - August 28th, 2023
    - December 25th, 2023
    - December 26th, 2023
  work_week:
    - mon
    - tue
    - wed
    - thu
    - fri
