default: &default
  adapter: postgis
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', '').sub(%r{^postgres://}, 'postgis://') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: bops_development
  cache:
    <<: *default
    database: bops_development_cache
    migrations_paths: db/cache_migrate

test:
  primary:
    <<: *default
    database: bops_test
  cache:
    <<: *default
    database: bops_test_cache
    migrations_paths: db/cache_migrate

production:
  primary:
    <<: *default
    database: bops_production
  cache:
    <<: *default
    database: bops_production_cache
    migrations_paths: db/cache_migrate
