test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  region: <%= (ENV["AWS_REGION"] || "eu-west-2").inspect %>
  bucket: <%= ENV["S3_BUCKET"].inspect %>
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"].inspect if ENV["HEROKU"].present? %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"].inspect if ENV["HEROKU"].present? %>
