---
name: Deploy production

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to production
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-name: "production"
    secrets: inherit
