name: Tag release
on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types: ["completed"]
jobs:
  tag-release:
    name: Tag release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Get current date
        id: date
        run: |
          date="$(date +%Y-%m-%dT%H.%M)"
          echo "date=$date" >>$GITHUB_OUTPUT
          echo "new_tag=release-$date" >>$GITHUB_OUTPUT

      - name: Create and push tag
        id: tag_version
        env:
          new_tag: ${{ steps.date.outputs.new_tag }}
        run: |
          set -e
          git tag -l "${new_tag}"
          git push --tags

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.date.outputs.new_tag }}
          name: Release ${{ steps.date.outputs.date }}
          body: "# Release ${{ steps.date.outputs.date }}"
          prerelease: true
          makeLatest: false
          token: ${{ secrets.DEPLOY_TOKEN }}
